"use client";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, FolderKanban, Activity, Users, Boxes, ClipboardCheck, ShieldCheck } from "lucide-react";
const sections=[
 {title:"Project Portfolio",desc:"Buat dan kelola kode proyek, kategori, status, anggaran, target, dan progres.",href:"/master-data/?tab=projects",label:"Kelola proyek",icon:FolderKanban},
 {title:"WBS & Schedule",desc:"Mulai alur pekerjaan proyek melalui Operations Studio; data rinci jadwal dapat dikembangkan per proyek.",href:"/operations/",label:"Buka Operations Studio",icon:Activity},
 {title:"Progress & Site Evidence",desc:"Buat engineering run yang terikat pada organisasi dan catat keluaran serta status review.",href:"/operations/",label:"Buka workflow",icon:ClipboardCheck},
 {title:"Team & Assignments",desc:"Kelola pegawai dan penempatan proyek dari master data agar penugasan tetap konsisten.",href:"/master-data/?tab=employees",label:"Kelola pegawai",icon:Users},
 {title:"Project Assets",desc:"Hubungkan aset dan penanggung jawab ke proyek dari register aset.",href:"/master-data/?tab=assets",label:"Kelola aset",icon:Boxes},
 {title:"QA/QC, HSE & Governance",desc:"Keputusan penting harus tetap melalui kontrol risiko, bukti, dan persetujuan manusia.",href:"/grc/",label:"Buka GRC",icon:ShieldCheck}
];
export default function ModulePage(){return <main className="nusa gridbg"><div style={{minHeight:"100vh",padding:"28px",maxWidth:1500,margin:"0 auto"}}><Link href="/" style={{display:"inline-flex",gap:8,alignItems:"center",color:"#a9d8b7",textDecoration:"none",fontSize:13}}><ArrowLeft size={16}/> Command Center</Link><header style={{marginTop:36,display:"flex",justifyContent:"space-between",alignItems:"end",gap:18,flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:12,letterSpacing:".12em"}}>NUSA / PROJECT ENGINEERING</div><h1 className="brand" style={{fontSize:42,margin:"8px 0 10px"}}>Projects & Construction</h1><p className="muted" style={{fontSize:15,lineHeight:1.7,maxWidth:850}}>Mulai dari master proyek yang valid, kemudian hubungkan tim, aset, dan workflow engineering dalam batas organisasi yang sama.</p></div><Link href="/master-data/?tab=projects" style={{display:"inline-flex",gap:8,alignItems:"center",padding:"12px 15px",borderRadius:10,background:"#d8f5df",color:"#0b2116",fontWeight:700,textDecoration:"none"}}><FolderKanban size={16}/> Kelola proyek <ArrowUpRight size={15}/></Link></header><div className="glass" style={{marginTop:22,padding:16,borderRadius:14,display:"flex",gap:12,alignItems:"center"}}><ShieldCheck size={19}/><div><b>Aturan hubungan data</b><div className="muted" style={{fontSize:12,marginTop:4,lineHeight:1.6}}>Setiap proyek dimiliki satu organisasi. Penempatan pegawai dan aset divalidasi agar tidak dapat menunjuk ke proyek milik organisasi lain.</div></div></div><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,300px),1fr))",gap:14,marginTop:16}}>{sections.map(s=>{const Icon=s.icon;return <article key={s.title} className="glass" style={{padding:18,borderRadius:14,minHeight:190,display:"flex",flexDirection:"column"}}><div style={{display:"flex",justifyContent:"space-between",color:"#a9d8b7"}}><Icon size={19}/><ArrowUpRight size={15}/></div><h2 style={{fontSize:17,margin:"16px 0 7px"}}>{s.title}</h2><p className="muted" style={{fontSize:12,lineHeight:1.6,margin:"0 0 18px",flex:1}}>{s.desc}</p><Link href={s.href} style={{color:"#a9d8b7",fontSize:12,textDecoration:"none",fontWeight:700}}>{s.label} →</Link></article>})}</section></div></main>}