import EnterpriseModuleHub from "../../components/EnterpriseModuleHub";
export default function Page(){return <EnterpriseModuleHub title="Procurement & Asset" eyebrow="NUSA / SUPPLY CHAIN & ASSET LIFECYCLE" description="Alur pengadaan dari permintaan sampai vendor, draf purchase order, dan persediaan. Nilai estimasi, PO, penerimaan barang, dan pembayaran adalah tahap berbeda serta harus mengikuti kewenangan." sections={[
{title:"Purchase Requisition",description:"Nomor PR, kategori, kuantitas, satuan, spesifikasi, kebutuhan tanggal, dan estimasi biaya.",href:"/procurement/requests/",label:"Buat permintaan",stage:"REQUEST"},
{title:"Vendor Qualification",description:"Kode dan tipe vendor, kelengkapan dokumen, status kualifikasi, dan penilaian risiko.",href:"/procurement/vendors/",label:"Kelola vendor",stage:"SUPPLIER"},
{title:"Purchase Order & Contract",description:"Nomor PO, referensi PR, vendor, jadwal pengiriman, termin, dan draf komersial.",href:"/procurement/orders/",label:"Kelola PO",stage:"COMMITMENT"},
{title:"Inventory & Materials",description:"SKU, lokasi penyimpanan, saldo referensi, reorder point, batch/lot, dan inspeksi material.",href:"/procurement/inventory/",label:"Kelola persediaan",stage:"STOCK"},
{title:"Warehouse Master",description:"Gudang utama/proyek/transit, kapasitas, penanggung jawab, dan status operasional.",href:"/procurement/warehouses/",label:"Kelola gudang",stage:"WAREHOUSE"},
{title:"Goods Receipt & QC",description:"Penerimaan terhadap PO, kuantitas, batch/lot, pemeriksaan kualitas, dan karantina.",href:"/procurement/receipts/",label:"Catat penerimaan",stage:"RECEIVING"},
{title:"Stock Movement",description:"Penerimaan, pengeluaran, transfer gudang, retur, dan penyesuaian berbasis referensi.",href:"/procurement/movements/",label:"Catat pergerakan",stage:"MOVEMENT"},
{title:"Stock Opname & Cycle Count",description:"Hitung fisik, rekonsiliasi selisih, investigasi, dan persetujuan adjustment.",href:"/procurement/stock-counts/",label:"Mulai stock opname",stage:"ASSURANCE"},
{title:"Project Material Issue",description:"Pengeluaran material dari gudang ke proyek/work package dengan serah terima.",href:"/procurement/project-issues/",label:"Catat material proyek",stage:"PROJECT ISSUE"}]} principles={["Aset tetap, material persediaan, dan komitmen pembelian mempunyai perlakuan berbeda; gunakan submenu sesuai siklus hidupnya.","Pembuatan draf tidak otomatis menerbitkan PO, melakukan goods receipt, mengubah valuasi persediaan, atau mengirim pembayaran."]}/>}