"use client";
import {useState} from "react";
import {Activity,ArrowUpRight,BarChart3,Building2,CircleDollarSign,ClipboardCheck,Command,FileText,Layers3,MessageSquare,PanelLeft,Plus,ShieldCheck,Users,Zap} from "lucide-react";
const modules=[["Command Center",Command],["Projects & Construction",Building2],["Engineering & SAP2000",Activity],["Architecture / CAD / BIM",Layers3],["ERP & Finance",CircleDollarSign],["CRM",Users],["HRD & Payroll",Users],["Procurement & Asset",ClipboardCheck],["Reports & Forecast",BarChart3],["GRC & Compliance",ShieldCheck]] as const;
const agents=[["NUSA Orchestrator","Coordinates multi-agent work","online"],["Structural Engineer","SNI / SAP2000 analysis","ready"],["QS & Cost Control","QTO / BOQ / RAB","ready"],["Field Vision QA","Progress / defect evidence","ready"],["Document Controller","Revision / audit trail","ready"]];
export default function Home(){const [open,setOpen]=useState(true);const [q,setQ]=useState("");const [messages,setMessages]=useState<string[]>([]);const ask=()=>{if(!q.trim())return;setMessages(m=>[...m,"NUSA menerima: "+q]);setQ("")};return <main className="nusa gridbg"><div style={{display:"grid",gridTemplateColumns:open?"272px 1fr":"72px 1fr",minHeight:"100vh"}}>
<aside className="glass" style={{padding:18,position:"sticky",top:0,height:"100vh"}}><button onClick={()=>setOpen(!open)} style={{background:"none",border:0,color:"white",cursor:"pointer"}}><PanelLeft/></button>{open&&<><div style={{margin:"22px 4px 28px"}}><div className="brand" style={{fontSize:23,fontWeight:700}}>NUSA</div><div className="muted" style={{fontSize:12}}>ENTERPRISE ENGINEERING OS</div></div>{modules.map(([name,Icon])=><div key={name} style={{display:"flex",gap:11,alignItems:"center",padding:"11px 8px",borderRadius:10,color:"#b9c9c1",fontSize:13}}><Icon size={17}/>{name}</div>)}<div style={{marginTop:20,padding:12,borderTop:"1px solid #20352d",fontSize:11}} className="muted">Phase 0 → Go Live<br/>Foundation active</div></>}</aside>
<section style={{padding:"24px 28px",maxWidth:1500,width:"100%",margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"}}><div><div className="muted" style={{fontSize:12}}>NUSA CONTROL PLANE / PRODUCTION BLUEPRINT</div><h1 className="brand" style={{fontSize:30,margin:"5px 0"}}>Enterprise Command Center</h1></div><div style={{display:"flex",gap:10}}><button className="glass" style={{padding:"10px 14px",color:"#dcebe4",borderRadius:10,border:0}}><FileText size={16}/></button><button style={{background:"#d8f5df",color:"#0b2116",border:0,borderRadius:10,padding:"10px 15px",fontWeight:700}}><Plus size={16}/> New Workspace</button></div></header>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginTop:24}}>{[["Active Projects","12","↑ 3 this month"],["Engineering Runs","48","96% verified"],["Open Issues","17","4 critical"],["Forecast Accuracy","94.2%","↑ 2.1%"]].map(([a,b,c])=><div className="glass" key={a} style={{padding:18,borderRadius:14}}><div className="muted" style={{fontSize:12}}>{a}</div><div className="brand" style={{fontSize:28,fontWeight:700,marginTop:8}}>{b}</div><div style={{fontSize:11,color:"#91c7a7",marginTop:4}}>{c}</div></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"1.5fr 1fr",gap:16,marginTop:16}}><div className="glass" style={{padding:20,borderRadius:16}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div className="muted" style={{fontSize:12}}>PILOT PROJECT</div><h2 style={{margin:"5px 0 3px",fontSize:20}}>Yayasan Islami–Kejawen · Ngawi</h2><div className="muted" style={{fontSize:12}}>26 × 8 m · 2 floors · Design Development</div></div><ArrowUpRight/></div><div style={{height:8,background:"#1c332a",borderRadius:10,marginTop:28}}><div style={{width:"72%",height:"100%",background:"#8ed8a6",borderRadius:10}}/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8,fontSize:12}}><span className="muted">Engineering workflow</span><b>72%</b></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginTop:22}}>{[["Structure","Preliminary"],["MEP","Coordinated"],["SAP2000","Awaiting site data"]].map(x=><div key={x[0]} style={{padding:12,background:"#0a1712",borderRadius:10}}><div className="muted" style={{fontSize:11}}>{x[0]}</div><div style={{fontSize:12,marginTop:5}}>{x[1]}</div></div>)}</div></div>
<div className="glass" style={{padding:20,borderRadius:16}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div className="muted" style={{fontSize:12}}>AI WORKFORCE</div><h2 style={{margin:"5px 0 18px",fontSize:20}}>Agent Fleet</h2></div><Zap size={18}/></div>{agents.map(a=><div key={a[0]} style={{display:"flex",gap:12,alignItems:"center",padding:"10px 0",borderBottom:"1px solid #173027"}}><div style={{width:8,height:8,borderRadius:50,background:"#8ed8a6"}}/><div style={{flex:1}}><div style={{fontSize:13}}>{a[0]}</div><div className="muted" style={{fontSize:10}}>{a[1]}</div></div><span style={{fontSize:10}}>{a[2]}</span></div>)}</div></div>
<div className="glass" style={{padding:18,borderRadius:16,marginTop:16}}><div style={{display:"flex",gap:12,alignItems:"center"}}><MessageSquare size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Tanyakan NUSA: analisa proyek, buat RAB, cek risiko, siapkan laporan..." style={{flex:1,background:"transparent",border:0,outline:0,color:"white",fontSize:14}}/><button onClick={ask} style={{background:"#d8f5df",border:0,borderRadius:9,padding:"9px 14px",fontWeight:700}}>ASK NUSA</button></div>{messages.length>0&&<div style={{marginTop:14,fontSize:12}}>{messages.slice(-3).map((m,i)=><div key={i} style={{padding:10,background:"#0a1712",borderRadius:8,marginTop:6}}>{m}</div>)}</div>}</div>
<footer className="muted" style={{fontSize:11,marginTop:18,display:"flex",justifyContent:"space-between"}}><span>Evidence-first · Human approval for critical engineering decisions</span><span>v0.1.0 · Foundation</span></footer></section></div></main>}