"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import Link from "next/link";
import {ArrowLeft,RefreshCw,Save,LockKeyhole,History,Plus} from "lucide-react";
import {supabase} from "../lib/supabase";
import {currentUser,myTenants} from "../lib/nusa";
type Tenant={id:string;name:string;code:string};
type Employee={id:string;employee_code:string;full_name:string;position_title:string|null;employment_status:string};
type Comp={id:string;tenant_id:string;employee_id:string;effective_from:string;effective_to:string|null;base_salary:number;fixed_allowance:number;position_allowance:number;overtime_rate:number;policy_reference:string|null;status:string;created_at:string};
type FormData={employee_id:string;effective_from:string;effective_to:string;base_salary:string;fixed_allowance:string;position_allowance:string;overtime_rate:string;policy_reference:string;status:string};
const blank:FormData={employee_id:"",effective_from:new Date().toISOString().slice(0,10),effective_to:"",base_salary:"",fixed_allowance:"0",position_allowance:"0",overtime_rate:"0",policy_reference:"",status:"active"};
const style:React.CSSProperties={width:"100%",boxSizing:"border-box",marginTop:6,padding:10,background:"#0b1712",color:"#e7f2eb",border:"1px solid #29463a",borderRadius:9,font:"inherit"};
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
export default function CompensationWorkspace(){
 const [userId,setUserId]=useState("");const [tenants,setTenants]=useState<Tenant[]>([]);const [tenantId,setTenantId]=useState("");const [employees,setEmployees]=useState<Employee[]>([]);const [rows,setRows]=useState<Comp[]>([]);const [form,setForm]=useState<FormData>(blank);const [editId,setEditId]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");const u=await currentUser();if(!u){setUserId("");setTenants([]);setEmployees([]);setRows([]);setLoading(false);return;}setUserId(u.id);const tr=await myTenants();if(tr.error){setError(tr.error.message);setLoading(false);return;}const ts=(tr.data??[]) as Tenant[];setTenants(ts);const tid=ts.some(t=>t.id===tenantId)?tenantId:(ts[0]?.id??"");setTenantId(tid);if(!tid){setEmployees([]);setRows([]);setLoading(false);return;}const [er,cr]=await Promise.all([supabase.from("nusa_employees").select("id,employee_code,full_name,position_title,employment_status").eq("tenant_id",tid).is("archived_at",null).order("full_name"),supabase.from("nusa_employee_compensation").select("id,tenant_id,employee_id,effective_from,effective_to,base_salary,fixed_allowance,position_allowance,overtime_rate,policy_reference,status,created_at").eq("tenant_id",tid).order("effective_from",{ascending:false})]);if(er.error)setError("Gagal memuat pegawai: "+er.error.message);else setEmployees((er.data??[]) as Employee[]);if(cr.error)setError("Akses kompensasi ditolak atau tabel belum tersedia: "+cr.error.message);else setRows((cr.data??[]) as Comp[]);setLoading(false);},[tenantId]);
 useEffect(()=>{const t=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(t);},[refresh]);
 function edit(row:Comp){setEditId(row.id);setForm({employee_id:row.employee_id,effective_from:row.effective_from,effective_to:row.effective_to??"",base_salary:String(row.base_salary),fixed_allowance:String(row.fixed_allowance),position_allowance:String(row.position_allowance),overtime_rate:String(row.overtime_rate),policy_reference:row.policy_reference??"",status:row.status});setError("");setNotice("");}
 function reset(){setEditId("");setForm({...blank,employee_id:employees.find(e=>e.employment_status==="active")?.id??""});}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!userId||!tenantId)return;if(form.effective_to&&form.effective_to<form.effective_from){setError("Tanggal akhir tidak boleh sebelum tanggal mulai.");return;}const values={tenant_id:tenantId,employee_id:form.employee_id,effective_from:form.effective_from,effective_to:form.effective_to||null,base_salary:Number(form.base_salary),fixed_allowance:Number(form.fixed_allowance||0),position_allowance:Number(form.position_allowance||0),overtime_rate:Number(form.overtime_rate||0),policy_reference:form.policy_reference.trim()||null,status:form.status,updated_by:userId};if([values.base_salary,values.fixed_allowance,values.position_allowance,values.overtime_rate].some(v=>!Number.isFinite(v)||v<0)){setError("Nilai kompensasi harus angka nol atau lebih.");return;}setSaving(true);setError("");setNotice("");let r;if(editId)r=await supabase.from("nusa_employee_compensation").update(values).eq("id",editId).eq("tenant_id",tenantId);else r=await supabase.from("nusa_employee_compensation").insert({...values,created_by:userId});if(r.error)setError("Gagal menyimpan profil kompensasi: "+r.error.message);else{setNotice("Profil kompensasi tersimpan dengan tanggal efektif. Perubahan tidak otomatis mengubah payroll yang sudah ditutup.");reset();await refresh();}setSaving(false);}
 const set=(k:keyof FormData,v:string)=>setForm(prev=>({...prev,[k]:v}));
 return <main className="nusa gridbg"><div style={{maxWidth:1380,margin:"0 auto",padding:"clamp(16px,3vw,32px)"}}><Link href="/hr/" style={{display:"inline-flex",gap:8,alignItems:"center",color:"#a9d8b7",textDecoration:"none",fontSize:12}}><ArrowLeft size={15}/> HRD & Payroll</Link><header style={{marginTop:26,display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:10,letterSpacing:".15em"}}>HR / RESTRICTED COMPENSATION MASTER</div><h1 className="brand" style={{fontSize:"clamp(30px,4vw,44px)",margin:"9px 0"}}>Compensation & Allowance Master</h1><p className="muted" style={{maxWidth:850,fontSize:13,lineHeight:1.8}}>Master kompensasi bertanggal efektif untuk gaji pokok, tunjangan tetap, tunjangan jabatan dan tarif lembur. Hanya role HR/Payroll/Finance yang ditentukan dapat membaca atau mengubahnya.</p></div><button onClick={()=>void refresh()} className="glass" style={{padding:"10px 13px",borderRadius:9,color:"#e7f2eb"}}><RefreshCw size={14} style={{verticalAlign:"middle",marginRight:6}}/>Muat ulang</button></header>
 {!userId?<section className="glass" style={{marginTop:18,padding:20,borderRadius:14}}>Sesi masuk diperlukan. <Link href="/" style={{color:"#a9d8b7"}}>Kembali ke Command Center</Link></section>:<><section className="glass" style={{marginTop:16,padding:15,borderRadius:12}}><label style={{fontSize:11}}>ORGANISASI<select value={tenantId} onChange={e=>{setTenantId(e.target.value);setEditId("");}} style={style}><option value="">Pilih organisasi</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.name} · {t.code}</option>)}</select></label></section>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,330px),1fr))",gap:14,marginTop:14,alignItems:"start"}}><section className="glass" style={{padding:17,borderRadius:13}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><h2 style={{fontSize:17,margin:0}}>{editId?"Ubah profil kompensasi":"Tambah profil kompensasi"}</h2><LockKeyhole size={17} color="#a9d8b7"/></div><form onSubmit={save} style={{display:"grid",gap:10,marginTop:14}}><label style={{fontSize:12}}>Pegawai *<select required value={form.employee_id} onChange={e=>set("employee_id",e.target.value)} style={style}><option value="">Pilih pegawai</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_code} · {e.full_name}{e.employment_status!=="active"?" (nonaktif)":""}</option>)}</select></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><label style={{fontSize:12}}>Berlaku mulai *<input required type="date" value={form.effective_from} onChange={e=>set("effective_from",e.target.value)} style={style}/></label><label style={{fontSize:12}}>Berlaku sampai<input type="date" value={form.effective_to} onChange={e=>set("effective_to",e.target.value)} style={style}/></label></div>{([["base_salary","Gaji pokok *"],["fixed_allowance","Tunjangan tetap"],["position_allowance","Tunjangan jabatan"],["overtime_rate","Tarif lembur per jam"]] as const).map(([key,label])=><label key={key} style={{fontSize:12}}>{label}<input required={key==="base_salary"} type="number" min="0" step="0.01" value={form[key]} onChange={e=>set(key,e.target.value)} style={style}/></label>)}<label style={{fontSize:12}}>Referensi kebijakan / keputusan HR<input value={form.policy_reference} onChange={e=>set("policy_reference",e.target.value)} placeholder="SK kompensasi / kontrak / kebijakan" style={style}/></label><label style={{fontSize:12}}>Status<select value={form.status} onChange={e=>set("status",e.target.value)} style={style}><option value="active">Aktif</option><option value="inactive">Nonaktif</option><option value="superseded">Digantikan</option></select></label><div style={{display:"flex",gap:8}}><button disabled={saving||loading||!tenantId} style={{flex:1,padding:11,border:0,borderRadius:9,background:"#a9d8b7",color:"#10251a",fontWeight:750}}><Save size={14} style={{verticalAlign:"middle",marginRight:6}}/>{saving?"Menyimpan…":"Simpan profil"}</button><button type="button" onClick={reset} className="glass" style={{padding:"10px 12px",borderRadius:9,color:"#e7f2eb"}}><Plus size={14} style={{verticalAlign:"middle",marginRight:5}}/>Baru</button></div></form><p className="muted" style={{fontSize:10,lineHeight:1.7}}>Periode efektif untuk satu pegawai tidak boleh saling tumpang tindih. Tutup tanggal akhir profil lama sebelum membuat profil baru.</p></section>
 <section className="glass" style={{padding:17,borderRadius:13,minWidth:0}}><div style={{display:"flex",gap:8,alignItems:"center"}}><History size={17} color="#a9d8b7"/><h2 style={{fontSize:17,margin:0}}>Riwayat kompensasi</h2></div>{loading?<p className="muted">Memuat data…</p>:rows.length===0?<p className="muted" style={{fontSize:12,lineHeight:1.7}}>Belum ada profil kompensasi atau role Anda tidak memiliki akses. Tambahkan pegawai terlebih dahulu di Master Data.</p>:<div style={{overflowX:"auto",marginTop:12}}><table style={{width:"100%",minWidth:690,borderCollapse:"collapse",fontSize:11}}><thead><tr>{["Pegawai","Efektif","Gaji pokok","Tunjangan","Tarif lembur","Status","Aksi"].map(x=><th key={x} style={{textAlign:"left",padding:9,borderBottom:"1px solid #29463a"}}>{x}</th>)}</tr></thead><tbody>{rows.map(r=>{const e=employees.find(x=>x.id===r.employee_id);return <tr key={r.id}><td style={{padding:9,borderBottom:"1px solid #1e3329"}}>{e?.employee_code} · {e?.full_name}</td><td style={{padding:9,borderBottom:"1px solid #1e3329"}}>{r.effective_from} — {r.effective_to??"berjalan"}</td><td style={{padding:9,borderBottom:"1px solid #1e3329"}}>{money(Number(r.base_salary))}</td><td style={{padding:9,borderBottom:"1px solid #1e3329"}}>{money(Number(r.fixed_allowance)+Number(r.position_allowance))}</td><td style={{padding:9,borderBottom:"1px solid #1e3329"}}>{money(Number(r.overtime_rate))}</td><td style={{padding:9,borderBottom:"1px solid #1e3329"}}>{r.status}</td><td style={{padding:9,borderBottom:"1px solid #1e3329"}}><button onClick={()=>edit(r)} className="glass" style={{padding:"6px 9px",borderRadius:7,color:"#a9d8b7"}}>Ubah</button></td></tr>})}</tbody></table></div>}</section></div></>}
 {error&&<p role="alert" style={{marginTop:12,padding:12,border:"1px solid #8b4949",borderRadius:9,color:"#ffc4c4"}}>{error}</p>}{notice&&<p role="status" style={{marginTop:12,padding:12,border:"1px solid #35674b",borderRadius:9,color:"#a9d8b7"}}>{notice}</p>}<div className="glass" style={{marginTop:14,padding:12,borderRadius:10,fontSize:11,lineHeight:1.7}}>Data kompensasi adalah data pribadi/finansial terbatas. Hasil payroll yang sudah disetujui tidak diubah otomatis oleh perubahan profil kompensasi berikutnya.</div></div></main>;
}
