"use client";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CheckCircle2, ShieldCheck } from "lucide-react";
const sections=["General Ledger","AP / AR","Cash & Bank","Budget & Cost Control","Tax & Closing","Management Finance"];
export default function ModulePage(){return <main className="nusa gridbg"><div style={{minHeight:"100vh",padding:"28px",maxWidth:1500,margin:"0 auto"}}>
<Link href="/" style={{display:"inline-flex",gap:8,alignItems:"center",color:"#a9d8b7",textDecoration:"none",fontSize:13}}><ArrowLeft size={16}/> Command Center</Link>
<header style={{marginTop:42,display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:12,letterSpacing:".12em"}}>NUSA / ERP & FINANCE</div><h1 className="brand" style={{fontSize:42,margin:"8px 0 10px"}}>ERP & Finance</h1><p className="muted" style={{fontSize:15,lineHeight:1.7,maxWidth:850}}>Finance, accounting, cash flow, budget, cost control, dan transaksi enterprise.</p></div><div className="glass" style={{padding:"10px 14px",borderRadius:999,fontSize:11}}><span style={{display:"inline-block",width:7,height:7,borderRadius:99,background:"#8ed8a6",marginRight:8}}/>GOVERNED WORKSPACE</div></header>
<div className="glass" style={{marginTop:24,padding:16,borderRadius:14,display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:10}}>WORKSPACE MAP</div><b>{sections.length} workstreams</b></div><div style={{display:"flex",gap:8}}><button className="glass" style={{padding:"9px 12px",borderRadius:9,color:"#dcebe4",border:0}}>Evidence</button><button className="glass" style={{padding:"9px 12px",borderRadius:9,color:"#dcebe4",border:0}}>History</button></div></div>
<section style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:14,marginTop:16}}>{sections.map((x:string)=><div key={x} className="glass" style={{padding:18,borderRadius:14,minHeight:165}}><div style={{display:"flex",justifyContent:"space-between"}}><CheckCircle2 size={18}/><ArrowUpRight size={15}/></div><h2 style={{fontSize:17,margin:"16px 0 7px"}}>{x}</h2><p className="muted" style={{fontSize:12,lineHeight:1.6}}>Workspace siap untuk implementasi data, workflow, evidence dan audit trail.</p><div style={{marginTop:18,fontSize:10,color:"#91c7a7"}}>IMPLEMENTATION SURFACE</div></div>)}</section>
<div className="glass" style={{marginTop:16,padding:16,borderRadius:14,display:"flex",gap:12,alignItems:"center"}}><ShieldCheck size={19}/><div><b>Evidence-first governance</b><div className="muted" style={{fontSize:11,marginTop:4}}>Perubahan penting memiliki jejak audit. Posted records menggunakan void, reverse atau archive; bukan silent delete.</div></div></div>
</div></main>}