import EnterpriseModuleHub from "../../components/EnterpriseModuleHub";
export default function Page(){return <EnterpriseModuleHub title="Enterprise Management Blueprint" eyebrow="NUSA / SYSTEM GOVERNANCE & CONTROL CATALOG" description="Peta sistem manajemen perusahaan dengan organisasi, transaksi, otorisasi, dokumen terkendali, audit evidence, dan alur lintas fungsi. Katalog ini membedakan fitur yang sudah tersedia dari target pengembangan; bukan klaim sertifikasi otomatis." sections={[
{title:"Master Data & Organization",description:"Entitas legal, cabang, departemen, cost centre, proyek, pegawai, pelanggan, vendor, SKU, gudang, aset, akun, dan data dictionary.",href:"/master-data/",label:"Buka master data",stage:"FOUNDATION"},
{title:"ERP & Finance",description:"GL, jurnal, AP/AR, cash management, anggaran, aset tetap, biaya, pajak, rekonsiliasi, dan period close.",href:"/erp/",label:"Buka ERP & Finance",stage:"WORKFLOW"},
{title:"HR, Attendance & Payroll",description:"Rekrutmen, kehadiran, cuti/sakit, lembur, pelatihan, komponen kompensasi, payroll review, dan kontrol akses.",href:"/hr/",label:"Buka HRD & Payroll",stage:"RESTRICTED"},
{title:"Procurement & Warehouse",description:"PR → vendor sourcing → PO → goods receipt/QC → gudang → pergerakan stok → stock opname → material issue ke proyek.",href:"/procurement/",label:"Buka procurement",stage:"SUPPLY CHAIN"},
{title:"CRM & Customer Lifecycle",description:"Lead, account/contact, quotation, aktivitas, kontrak/proyek, milestone billing, layanan pelanggan, dan collection handoff.",href:"/crm/",label:"Buka CRM",stage:"REVENUE"},
{title:"Project & Construction Controls",description:"WBS/BOQ, baseline jadwal/biaya, change order, RFI, inspeksi, NCR/CAPA, progress claim, dan closeout.",href:"/projects/",label:"Buka proyek",stage:"DELIVERY"},
{title:"Engineering, CAD/BIM & GIS",description:"Design basis, perhitungan, review independen, revision control, BIM/IFC, clash review, spatial data, dan bukti lapangan.",href:"/operations/",label:"Buka engineering",stage:"TECHNICAL"},
{title:"GRC, Quality, HSE & Compliance",description:"Risk register, audit, CAPA, obligations, incident investigation, information security, privacy, and business continuity.",href:"/grc/",label:"Buka GRC",stage:"ASSURANCE"},
{title:"Reports, BI & Forecast",description:"KPI dictionary, sumber dan freshness data, financial/project dashboards, scenario, report packs, dan management review.",href:"/reports/",label:"Buka laporan",stage:"PERFORMANCE"},
{title:"AURA & AI Runtime",description:"Avatar voice, contextual assistant, document intelligence, multi-agent workflows, and permission-aware human approvals.",href:"/aura/",label:"Buka AURA",stage:"COGNITIVE"}
]} principles={["Standar yang dipetakan antara lain ketentuan Indonesia yang berlaku, SAK/PSAK, perpajakan/BPJS, UU PDP, ISO 9001/14001/45001/27001/22301/31000/37301, ISO 21502, ISO 19650, dan SNI yang relevan. Edisi serta applicability wajib diverifikasi oleh pemilik proses/tenaga ahli.","Gunakan label Implemented & tested, Workflow/register, Prototype, atau Planned. Form yang tersimpan bukan otomatis jurnal final, saldo stok, hasil payroll, dokumen pajak resmi, atau sertifikasi ISO. Lihat docs/ENTERPRISE_MANAGEMENT_BLUEPRINT.md untuk katalog lengkap dan acceptance gate."]}/>}