import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
const assert = (ok, message) => { if (!ok) throw new Error("ACCEPTANCE FAIL: " + message); };

const governance = read("supabase/migrations/0007_nusa_engineering_governance.sql");
const ingestion = read("supabase/migrations/0006_nusa_ingestion.sql");
const operations = read("lib/operations.ts");
const rls = read("supabase/tests/nusa_rls.sql");
const smoke = read("scripts/smoke.mjs");
const master = read("supabase/migrations/20261009012000_nusa_master_data_crud.sql");
const onboarding = read("supabase/migrations/20261009014000_nusa_workspace_onboarding_invoker.sql");
const masterPage = read("app/master-data/page.tsx");
const operationsPage = read("app/operations/page.tsx");
const approvalDecision = read("supabase/migrations/20261009015000_nusa_atomic_approval_decision.sql");
const workspaceUi = read("components/EnterpriseWorkspace.tsx");
const financeUi = read("components/FinanceWorkspace.tsx");
const auraPage = read("app/aura/page.tsx");
const homePage = read("app/page.tsx");
const masterUi = read("app/master-data/page.tsx");
const auraAvatar = read("components/AuraVoiceAvatar.tsx");
const layout = read("app/layout.tsx");
const engineeringUi = read("components/EngineeringDisciplineWorkspace.tsx");
const moduleHubUi = read("components/EnterpriseModuleHub.tsx");
const architecturePage = read("app/architecture/page.tsx");
const operationsPageLive = read("app/operations/page.tsx");


assert(governance.includes("status text not null default 'queued' check(status in ('queued','running','review','approved','rejected','completed','failed','cancelled'))"), "engineering run status enum missing");
assert(governance.includes("criticality text not null default 'normal' check(criticality in ('normal','high','critical'))"), "engineering criticality enum missing");
assert(governance.includes("source_hash text"), "engineering provenance source_hash missing");
assert(governance.includes("evidence jsonb not null"), "engineering evidence field missing");
assert(governance.includes("nusa_engineering_runs_member_insert"), "engineering insert RLS missing");
assert(governance.includes("nusa_engineering_runs_member_update"), "engineering update RLS missing");
assert(governance.includes("nusa_approvals_member_select"), "approval select RLS missing");
assert(governance.includes("nusa_approvals_member_update"), "approval update RLS missing");
assert(operations.includes("input.criticality === \"critical\" || input.criticality === \"high\""), "application approval gate missing");
assert(operations.includes('approval_type: "engineering_review"'), "engineering approval record missing");

assert(ingestion.includes("source_hash text"), "ingestion source_hash missing");
assert(ingestion.includes("content_hash text"), "ingestion document content_hash missing");
assert(ingestion.includes("status text not null default 'queued' check (status in ('queued','extracting','classifying','chunking','review','published','rejected','failed'))"), "ingestion status enum missing");
assert(ingestion.includes("nusa_ingestion_jobs_member_insert"), "ingestion insert RLS missing");
assert(ingestion.includes("nusa_ingestion_jobs_member_update"), "ingestion update RLS missing");
assert(ingestion.includes("nusa_ingestion_documents_member_insert"), "document insert RLS missing");

assert(/relrowsecurity/.test(rls), "RLS test does not inspect RLS enablement");
assert(smoke.includes("Run & Approval Queue"), "smoke coverage missing governance queue");
assert(smoke.includes("Ingestion Queue"), "smoke coverage missing ingestion queue");
assert(master.includes("create table if not exists public.nusa_employees"), "employee master table missing");
assert(master.includes("create table if not exists public.nusa_assets"), "asset master table missing");
assert(master.includes("nusa_employees_project_tenant_fk"), "employee project tenant binding missing");
assert(master.includes("nusa_assets_employee_tenant_fk"), "asset employee tenant binding missing");
assert(master.includes("nusa_master_data_events"), "master data audit trail missing");
assert(master.includes("alter table public.nusa_employees enable row level security"), "employee RLS missing");
assert(master.includes("alter table public.nusa_assets enable row level security"), "asset RLS missing");
assert(onboarding.includes("security invoker"), "workspace onboarding should respect explicit RLS policies");
assert(onboarding.includes("(select auth.uid()) is null"), "workspace onboarding must require an authenticated actor");
assert(onboarding.includes("nusa_tenants_creator_insert"), "tenant creator insert policy missing");
assert(onboarding.includes("nusa_memberships_owner_self_insert"), "owner membership insert policy missing");
assert(onboarding.includes("revoke all on function public.nusa_create_workspace"), "workspace RPC grants must be restricted");
assert(masterPage.includes("createOrganization"), "organization onboarding action missing");
assert(masterPage.includes("async function submit"), "master data create/update action missing");
assert(masterPage.includes("async function archive"), "master data archive action missing");
assert(operationsPage.includes("reviewerAllowed"), "reviewer authorization state missing");
assert(operationsPage.includes("Setujui"), "approval decision action missing");
assert(operationsPage.includes("Tolak"), "approval rejection action missing");
assert(operationsPage.includes("nusa_decide_approval"), "approval UI must call the atomic decision RPC");
assert(approvalDecision.includes("security invoker"), "approval RPC must respect RLS");
assert(approvalDecision.includes("requester cannot approve their own request"), "approval RPC must prevent self-approval");
assert(approvalDecision.includes("update public.nusa_engineering_runs"), "approval decision must transition the linked run");

assert(workspaceUi.includes('titleLabel:"Nama transaksi / dokumen"'), "ERP contextual form fields missing");
assert(workspaceUi.includes('titleLabel:"Nama pelanggan / peluang"'), "CRM contextual form fields missing");
assert(workspaceUi.includes('titleLabel:"Nama kebutuhan SDM / aktivitas"'), "HR contextual form fields missing");
assert(workspaceUi.includes('titleLabel:"Nama barang / jasa yang dibutuhkan"'), "Procurement contextual form fields missing");
assert(workspaceUi.includes('titleLabel:"Nama laporan / analisis"'), "Reports contextual form fields missing");
assert(workspaceUi.includes('titleLabel:"Nama risiko / temuan / kontrol"'), "GRC contextual form fields missing");
assert(workspaceUi.includes('schema_version:1'), "workspace contextual data schema version missing");
assert(workspaceUi.includes('summaryKeys.filter'), "contextual record summary missing");
assert(auraPage.includes("AURA Integration Hub"), "AURA integration hub page missing");
assert(auraPage.includes("https://github.com/akvisomr-eng/AURA"), "official AURA source link missing");
assert(auraPage.includes("tidak berpura-pura bahwa koneksi runtime langsung sudah aktif"), "AURA runtime boundary disclosure missing");
assert(homePage.includes('["AURA Integration", Activity, "/aura/"]'), "AURA navigation entry missing");
assert(masterUi.includes('Muat 25 data contoh'), "25-record master-data seed action missing");
assert(masterUi.includes('DEMO-PRJ-05') && masterUi.includes('DEMO-EMP-10') && masterUi.includes('DEMO-AST-10'), "25 master-data sample definitions missing");
assert(masterUi.includes('created_by:userId,updated_by:userId'), "demo data must preserve authenticated actor audit fields");
assert(masterUi.includes('NUSA Demo Engineering (DATA CONTOH)'), "empty tenant onboarding demo missing");
assert(financeUi.includes('Bagan Akun'), "finance chart of accounts module missing");
assert(financeUi.includes('Jurnal Umum'), "finance journal module missing");
assert(financeUi.includes('Buku Besar'), "finance general ledger module missing");
assert(financeUi.includes('Kas & Bank'), "finance cash/bank module missing");
assert(financeUi.includes('Piutang Usaha'), "finance receivables module missing");
assert(financeUi.includes('Utang Usaha'), "finance payables module missing");
assert(financeUi.includes('Anggaran & Forecast'), "finance budget module missing");
assert(financeUi.includes('Pajak & Kepatuhan'), "finance tax module missing");
assert(financeUi.includes('Laporan Keuangan'), "finance reporting module missing");
assert(financeUi.includes('Rekonsiliasi Bank'), "finance bank reconciliation module missing");
assert(financeUi.includes('Biaya & Klaim'), "finance expense claims module missing");
assert(financeUi.includes('Aset Tetap'), "finance fixed assets module missing");
assert(financeUi.includes('Pusat Biaya'), "finance cost centers module missing");
assert(financeUi.includes('Tutup Buku'), "finance period close module missing");
assert(financeUi.includes('Total rekaman'), "finance overview KPI missing");
assert(financeUi.includes('financeQuery.eq("record_type",c.recordType):financeQuery'), "overview must query all ERP records while module pages are record-type scoped");
for (const route of ["bank-reconciliation","expenses","fixed-assets","cost-centers","period-close"]) assert(read("app/erp/"+route+"/page.tsx").includes('FinanceWorkspace'), "finance route missing: "+route);

assert(financeUi.includes('debit harus sama dengan kredit'), "journal balancing validation missing");
assert(financeUi.includes('nusa_workspace_records'), "finance records must persist to tenant-scoped storage");
assert(financeUi.includes('Jurnal Berulang'), "recurring journal module missing");
assert(financeUi.includes('Batch Pembayaran'), "payment run module missing");
assert(financeUi.includes('Forecast Arus Kas'), "cash forecast module missing");
assert(financeUi.includes('Dimensi Keuangan'), "financial dimensions module missing");
assert(financeUi.includes('Transaksi Antar-Entitas'), "intercompany module missing");
assert(financeUi.includes('Profitabilitas Proyek'), "project profitability module missing");
assert(financeUi.includes('monthlyActivity'), "six-month finance activity visualization missing");
assert(financeUi.includes('FINANCE CONTROL DESK'), "finance quick-action desk missing");
assert(financeUi.includes('bukan arus kas aktual'), "finance dashboard must distinguish register activity from actual cash flow");
for (const route of ["recurring-journals","payment-runs","cash-forecast","financial-dimensions","intercompany","project-profitability"]) assert(read("app/erp/"+route+"/page.tsx").includes('FinanceWorkspace'), "finance contextual route missing: "+route);

for (const route of ["chart-of-accounts","journals","general-ledger","cash-bank","receivables","payables","budgets","tax","reports"]) assert(read("app/erp/"+route+"/page.tsx").includes('FinanceWorkspace'), "finance route missing: "+route);

assert(moduleHubUi.includes("Module control center"), "module hub must provide contextual process navigation");
assert(auraAvatar.includes('/crm/leads/'), "AURA voice navigation to CRM submodules missing");
assert(auraAvatar.includes('/operations/structural-analysis/'), "AURA voice navigation to engineering submodules missing");
assert(auraAvatar.includes('/erp/journals/'), "AURA voice navigation to finance submodules missing");
assert(auraAvatar.includes('/erp/expenses/') && auraAvatar.includes('/erp/reports/'), "AURA voice navigation to expenses and financial reports missing");
assert(auraAvatar.includes('aura-avatar-launcher'), "AURA must render as a floating voice avatar, not a data table/form");
assert(auraAvatar.includes('aura-voice-orb-stage') && auraAvatar.includes('Mulai bicara'), "AURA voice-first avatar controls missing");
assert(!auraAvatar.includes('aura-voice-compose') && !auraAvatar.includes('Tulis pertanyaan untuk AURA'), "AURA primary interface must not be a text-entry form");
assert(layout.includes('AuraVoiceAvatar'), "AURA voice avatar must be mounted globally across NUSA routes");

for (const key of ["leads","contacts","quotations","activities"]) assert(workspaceUi.includes(key+":"), "CRM contextual workflow missing: "+key);
for (const key of ["recruitment","attendance","training","payroll"]) assert(workspaceUi.includes(key+":"), "HR contextual workflow missing: "+key);
for (const key of ["requests","vendors","orders","inventory"]) assert(workspaceUi.includes(key+":"), "Procurement contextual workflow missing: "+key);
for (const key of ["kpi","forecast","packs","scenarios"]) assert(workspaceUi.includes(key+":"), "Reports contextual workflow missing: "+key);
for (const key of ["risks","audit","compliance","incidents"]) assert(workspaceUi.includes(key+":"), "GRC contextual workflow missing: "+key);
for (const key of ["structural-analysis","geotechnical","sap2000-model","mep-coordination","quantity-surveying","site-inspection","cad-drawings","bim-coordination","clash-review","design-review","spatial-data"]) assert(engineeringUi.includes('"'+key+'":{'), "Engineering discipline schema missing: "+key);
assert(engineeringUi.includes("createEngineeringRun"), "discipline forms must create actual engineering workflow records");
assert(engineeringUi.includes("schema_version:1"), "engineering workflow payload schema version missing");
assert(engineeringUi.includes("human approval"), "engineering high/critical review disclosure missing");
assert(architecturePage.includes("/architecture/cad-drawings/") && architecturePage.includes("/architecture/bim-coordination/"), "architecture cards must link to dedicated workspaces");
assert(operationsPageLive.includes("/operations/structural-analysis/") && operationsPageLive.includes("/operations/geotechnical/"), "operations page must expose dedicated discipline submenus");
for (const route of ["leads","contacts","quotations","activities"]) assert(read("app/crm/"+route+"/page.tsx").includes('section="'+route+'"'), "CRM route missing: "+route);
for (const route of ["recruitment","attendance","training"]) assert(read("app/hr/"+route+"/page.tsx").includes('section="'+route+'"'), "HR route missing: "+route);
for (const route of ["requests","vendors","orders","inventory"]) assert(read("app/procurement/"+route+"/page.tsx").includes('section="'+route+'"'), "Procurement route missing: "+route);
for (const route of ["kpi","forecast","packs","scenarios"]) assert(read("app/reports/"+route+"/page.tsx").includes('section="'+route+'"'), "Reports route missing: "+route);
for (const route of ["risks","audit","compliance","incidents"]) assert(read("app/grc/"+route+"/page.tsx").includes('section="'+route+'"'), "GRC route missing: "+route);

const projectDemo = read("app/master-data/page.tsx");
assert(projectDemo.includes('code:"DEMO-PRJ-05"') && !projectDemo.includes('code:"DEMO-PRJ-06"'), "master-data demo must contain exactly five project templates");
assert(projectDemo.includes('record_code:"DEMO-PAY-"+n'), "demo portfolio must include payroll records");
assert(projectDemo.includes('record_type:"hr_attendance"') && projectDemo.includes('attendance_status:"Terverifikasi"'), "demo attendance records must be seeded as verified");
assert(projectDemo.includes('nusa_employee_compensation') && projectDemo.includes('nusa_payroll_lines') && projectDemo.includes('payroll_run'), "demo payroll must include restricted compensation and payroll run data");
assert(projectDemo.includes('record_code:"DEMO-BUD-"+n') && projectDemo.includes('record_code:"DEMO-AR-"+n') && projectDemo.includes('record_code:"DEMO-AP-"+n') && projectDemo.includes('record_code:"DEMO-EXP-"+n'), "demo portfolio must include linked ERP finance registers");
assert(projectDemo.includes('PROJECT DOSSIER') && projectDemo.includes('openProjectDetail'), "project detail dossier action missing");
assert(projectDemo.includes('Cetak / PDF') && projectDemo.includes('openMasterDetail'), "master data detail and print actions missing");
assert(projectDemo.includes('wCount.count??0)<25'), "sample seed must verify 20 ERP/Finance and 5 payroll records");
assert(financeUi.includes('async function archiveRecord'), "finance record archive action missing");
assert(financeUi.includes('function startEdit(row:Row)'), "finance record edit action missing");
assert(financeUi.includes('setDetailRow(r)'), "finance record detail view action missing");
assert(financeUi.includes('Cetak / PDF'), "finance record print action missing");
assert(workspaceUi.includes("function startEdit(row:RecordRow)"), "enterprise workspace edit action missing");
assert(workspaceUi.includes("setDetailRow(row)"), "enterprise workspace detail view missing");
assert(workspaceUi.includes("Cetak / PDF"), "enterprise workspace print action missing");
assert(workspaceUi.includes("updateStatus(row,\"archived\")"), "enterprise workspace archive action missing");

const blueprint = read("docs/ENTERPRISE_MANAGEMENT_BLUEPRINT.md");
const payrollSchema = read("supabase/migrations/20261009122455_nusa_restricted_payroll.sql");
const compensationSchema = read("supabase/migrations/20261009123000_nusa_employee_compensation.sql");
const payrollAuditSchema = read("supabase/migrations/20261009125000_nusa_payroll_audit.sql");
const payrollTransition = read("supabase/migrations/20261009130000_nusa_payroll_transition_guard.sql");
const payrollIndexes = read("supabase/migrations/20261009124000_nusa_payroll_fk_indexes.sql");
const compensationUi = read("components/CompensationWorkspace.tsx");
const payrollUi = read("components/PayrollWorkspace.tsx");
assert(blueprint.includes("three-way match") && blueprint.includes("ISO 22301") && blueprint.includes("ISO 19650"), "enterprise blueprint lacks cross-functional controls or standards mapping");
assert(read("app/system-blueprint/page.tsx").includes("/procurement/"), "enterprise blueprint route missing supply-chain links");
assert(workspaceUi.includes("const activeRecordType=recordType;") && workspaceUi.includes('recordQuery=recordQuery.eq("record_type",activeRecordType)'), "workspace registers must isolate each submenu by its record type");
for (const route of ["warehouses","receipts","movements","stock-counts","project-issues"]) assert(read("app/procurement/"+route+"/page.tsx").includes('moduleCode="procurement"'), "warehouse workflow route missing: "+route);
assert(payrollUi.includes('nusa_payroll_runs') && payrollUi.includes('nusa_payroll_lines'), "payroll UI must use dedicated restricted payroll tables");
assert(payrollUi.includes('approved_overtime_hours') && payrollUi.includes('sick_leave_days') && payrollUi.includes('unpaid_leave_days'), "payroll must consume approved attendance and leave fields");
assert(payrollUi.includes('bpjs_health_employee') && payrollUi.includes('bpjs_employment_employee') && payrollUi.includes('pph21') && payrollUi.includes('thr'), "payroll components missing");
assert(payrollSchema.includes("alter table public.nusa_payroll_runs enable row level security") && payrollSchema.includes("alter table public.nusa_payroll_lines enable row level security"), "payroll RLS must be enabled");
assert(payrollSchema.includes("approved_by <> prepared_by") && payrollSchema.includes("Independent finance approver role required"), "payroll must prevent self-approval");
assert(payrollSchema.includes("nusa_workspace_records(id)"), "payroll line must preserve attendance source evidence");
assert(compensationSchema.includes("alter table public.nusa_employee_compensation enable row level security") && compensationSchema.includes("Effective compensation periods cannot overlap"), "compensation master needs restricted RLS and non-overlapping effective dates");
assert(compensationUi.includes("effective_from") && compensationUi.includes("position_allowance") && compensationUi.includes("overtime_rate"), "compensation master fields missing");
assert(payrollAuditSchema.includes("nusa_capture_payroll_event") && payrollAuditSchema.includes("grant select on public.nusa_payroll_events to authenticated"), "payroll audit trail missing or not read-only to users");
assert(payrollTransition.includes("old.status<>'finance_review'") && payrollTransition.includes("Payroll must contain at least one employee line") && payrollTransition.includes("Payment evidence reference is required"), "payroll approval and payment transition guards missing");
assert(payrollIndexes.includes("idx_nusa_payroll_lines_attendance_record_id"), "payroll attendance foreign-key index missing");
assert(payrollUi.includes("Audit evidence payroll"), "payroll audit history view missing");
assert(payrollUi.includes("nusa_employee_compensation") && payrollUi.includes("chooseEmployee"), "payroll must preload effective-dated compensation");
assert(read("app/hr/page.tsx").includes("/hr/compensation/"), "HR hub must link compensation master");

console.log("NUSA operational acceptance static assertions: PASS");
