"use client";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CheckCircle2, ShieldCheck, Layers3, FolderKanban, Activity, Boxes } from "lucide-react";
const sections=[
 {title:"Spatial Workspace",desc:"Bentuk geometri proyek, lihat pratinjau denah 2D dan massa 3D, serta unduh geometry manifest untuk pengembangan lanjutan.",href:"/architecture/spatial-data/",label:"Kelola data spasial",icon:Layers3},
 {title:"CAD / DWG / DXF",desc:"Buat denah konsep berdimensi dan ekspor DXF R12, SVG, serta metadata geometri. DWG native memerlukan konversi melalui perangkat CAD yang kompatibel.",href:"/architecture/cad-drawings/",label:"Buka drawing register",icon:FolderKanban},
 {title:"BIM / IFC",desc:"Pilih proyek dan mulai workflow koordinasi; pertukaran model IFC belum dianggap aktif sampai bridge tersedia.",href:"/architecture/bim-coordination/",label:"Buka BIM coordination",icon:Layers3},
 {title:"Clash & Coordination",desc:"Ajukan run koordinasi lintas disiplin dengan bukti dan review manusia.",href:"/architecture/clash-review/",label:"Kelola clash & issues",icon:Activity},
 {title:"Design Review",desc:"Tinjau asumsi desain dan kajian teknis, lalu ekspor denah CAD dan massa 3D konseptual sebelum review profesional.",href:"/architecture/design-review/",label:"Buka design review",icon:CheckCircle2},
 {title:"Project Assets",desc:"Kelola material dan aset proyek dari register master data, lalu tautkan ke proyek terkait.",href:"/master-data/?tab=assets",label:"Kelola aset",icon:Boxes}
];
export default function ModulePage(){return <main className="nusa gridbg"><div style={{minHeight:"100vh",padding:"28px",maxWidth:1500,margin:"0 auto"}}><Link href="/" style={{display:"inline-flex",gap:8,alignItems:"center",color:"#a9d8b7",textDecoration:"none",fontSize:13}}><ArrowLeft size={16}/> Command Center</Link><header style={{marginTop:36,display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:12,letterSpacing:".12em"}}>NUSA / ARCHITECTURE ENGINEERING</div><h1 className="brand" style={{fontSize:42,margin:"8px 0 10px"}}>Architecture / CAD / BIM</h1><p className="muted" style={{fontSize:15,lineHeight:1.7,maxWidth:850}}>Satu pintu untuk geometri, denah CAD konseptual, massa 3D, BIM/IFC, koordinasi dan kajian teknis. Keluaran yang bisa diunduh dibedakan secara jelas dari fitur yang masih membutuhkan bridge desktop.</p></div><div className="glass" style={{padding:"10px 14px",borderRadius:999,fontSize:11}}><span style={{display:"inline-block",width:7,height:7,borderRadius:99,background:"#8ed8a6",marginRight:8}}/>WORKSPACE TERHUBUNG</div></header><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,300px),1fr))",gap:14,marginTop:24}}>{sections.map(s=>{const Icon=s.icon;return <article key={s.title} className="glass" style={{padding:18,borderRadius:14,minHeight:180,display:"flex",flexDirection:"column"}}><div style={{display:"flex",justifyContent:"space-between",color:"#a9d8b7"}}><Icon size={18}/><ArrowUpRight size={15}/></div><h2 style={{fontSize:17,margin:"16px 0 7px"}}>{s.title}</h2><p className="muted" style={{fontSize:12,lineHeight:1.6,margin:"0 0 18px",flex:1}}>{s.desc}</p><Link href={s.href} style={{color:"#a9d8b7",fontSize:12,textDecoration:"none",fontWeight:700}}>{s.label} →</Link></article>})}</section><div className="glass" style={{marginTop:16,padding:16,borderRadius:14,display:"flex",gap:12,alignItems:"start"}}><ShieldCheck size={19}/><div><b>Evidence-first governance</b><div className="muted" style={{fontSize:11,marginTop:4,lineHeight:1.7}}>Hasil desain struktural, geoteknik, atau engineering berisiko tinggi tidak boleh diperlakukan sebagai keluaran final tanpa pemeriksaan profesional dan persetujuan manusia.</div></div></div></div></main>}